---
title: "Cartogram Tutorial"
output:
  html_document:  
    toc: true  
    toc_float: true 
    theme: flatly
    highlight: tango
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# load packages
library(ggplot2)
library(scales)
library(plyr)
library(dplyr)
library(tidyr)
library(extrafont)
library(rgdal)
library(viridis)


### read in data to append
df <- read.csv('C:/Users/jenniferb/OneDrive - Sport England/Power BI/Active Lives Survey/Gender_May1819_LA_CC_Regv2.csv')

df <- df %>%
  select('lad19cd', 'Male.Active')
range(df$Male.Active)

#import shapefile
setwd("C:/Users/jenniferb/OneDrive - Sport England/GitHub/Geographical Data/LAD/Local_Authority_Districts_April_2019_Boundaries_UK_BUC")
map1 <- readOGR(dsn = ".", layer = "Local_Authority_Districts_April_2019_Boundaries_UK_BUC", verbose = FALSE)
summary(map1) # see if projections used 

## map without distortion
map1@data$id <- rownames(map1@data)
map1@data   <- join(map1@data, df, by="lad19cd")
map.clean     <- fortify(map1)
map.clean     <- join(map.clean,map1@data, by="id")

map.clean <- map.clean[grep("E", map.clean$lad19cd),] # England only
map.clean <- map.clean[, !duplicated(colnames(map.clean))] # remove dupe cols



```


```{r test_map, eval=FALSE, message=FALSE, warning=FALSE, include=FALSE}
ggplot() +
  geom_polygon(data = map.clean, aes(x = long, y = lat, group = group, fill = Male.Active))+
  theme_minimal() + 
  theme(axis.title.x = element_blank(),axis.title.y = element_blank(), 
        text = element_text(family = "Poppins", color = "#5F5F5F"), 
        plot.title=element_text(size=14,family = "Poppins", face="bold", hjust = 0.5),
        panel.grid = element_blank(), 
        axis.text = element_blank(),
        axis.ticks.x = element_blank())+
  scale_fill_gradient(high = '#f7fcfd', low = '#00441b',
                      name='% of Active Males', breaks = 0.1*0:9, labels = percent(0.1*0:9))


```

# Basic Cartogram


```{r test_cart, echo=FALSE, fig.align='center', message=FALSE, warning=FALSE}
# load package
library(cartogram)

## create cartogram
test_cart <- cartogram_cont(map1, "Male.Active")
test_cart.1 <- cartogram_ncont(map1, "Male.Active", k = 10)

# check with basic plot
plot(test_cart)

```

# Cartogram using `GGPLOT`

```{r map, echo=FALSE, fig.align='center', message=FALSE, warning=FALSE}

# make into dataframe
map1.df     <- fortify(test_cart)
map1.df     <- join(map1.df,test_cart@data, by="id")


## remove dupe col
map1.df <- map1.df[, !duplicated(colnames(map1.df))]


ggplot() +
  geom_polygon(data = map1.df, aes(x = long, y = lat, group = group, fill = Male.Active))+
  theme_minimal() + 
  theme(axis.title.x = element_blank(),axis.title.y = element_blank(), 
        text = element_text(family = "Poppins", color = "#5F5F5F"), 
        plot.title=element_text(size=14,family = "Poppins", face="bold", hjust = 0.5),
        panel.grid = element_blank(), 
        axis.text = element_blank(),
        axis.ticks.x = element_blank())+
  scale_fill_gradient(high = '#f7fcfd', low = '#00441b',
                      name='% of Active Males', breaks = 0.1*0:9, labels = percent(0.1*0:9))
```


# Non-contiguous Cartogram using `GGPLOT`

```{r map1, echo=FALSE, fig.align='center', message=FALSE, warning=FALSE}

# make into dataframe
map2.df     <- fortify(test_cart.1)
map2.df     <- join(map2.df,test_cart.1@data, by="id")


## remove dupe col
map2.df <- map2.df[, !duplicated(colnames(map2.df))]


ggplot() +
  geom_polygon(data = map2.df, aes(x = long, y = lat, group = group, fill = Male.Active))+
  theme_minimal() + 
  theme(axis.title.x = element_blank(),axis.title.y = element_blank(), 
        text = element_text(family = "Poppins", color = "#5F5F5F"), 
        plot.title=element_text(size=14,family = "Poppins", face="bold", hjust = 0.5),
        panel.grid = element_blank(), 
        axis.text = element_blank(),
        axis.ticks.x = element_blank())+
  scale_fill_gradient(high = '#f7fcfd', low = '#00441b',
                      name='% of Active Males', breaks = 0.1*0:9, labels = percent(0.1*0:9))
```

